### ISSUE TITLE
Using threads while looping on events

### ISSUE THREAD

**Issue by eleguirriec** [KM3NeT/KM3io.jl#1]
Running this with --threads=2 is failing 

`using KM3io, KM3NeTTestData

f = ROOTFile(datapath("offline", "numucc.root"))

Threads.@threads for ev in f.offline
#for ev in f.offline
    @show ev
end`

It is running fine without threads (comment out for loop)

**Comment by tamasgal** [comment]
Issue copied to the original repository: https://git.km3net.de/common/KM3io.jl/-/issues/25
